blueprint:
  name: Theme Park Assistant - Recommended Attraction Actionable Notification
  description: Set up to send an actionable notification when a recommended attraction updates
  domain: automation
  author: BottlecapDave
  input:
    todo_list:
      name: Remaining Attractions
      description: The todo list of remaining attractions
      selector:
        entity:
          filter:
          - domain:
            - todo
            integration: theme_park_assistant
          multiple: false
    actions:
      name: Alert action
      description: Notifications or similar to be run. Action of {{action_complete}} should be called to remove the recommended attraction/show
        when redemption is successful. {{message}} is constructed based on the data
      selector:
        action: {}
variables:
  todo_list: !input todo_list
  actions: !input actions
mode: queued
max: 4
trigger:
- platform: event
  event_type: theme_park_assistant_new_recommended_attraction
condition: []
action:
# inside a automation actions or script sequence
- alias: "Set up variables for the actions"
  variables:
    action_complete: "{{ 'COMPLETE_' ~ context.id }}"
    action_ignore: "{{ 'IGNORE_' ~ context.id }}"
    message: >
      {% if trigger.event.data.is_show %}
      {{ trigger.event.data.attraction_name }} is recommended. It starts in {{ trigger.event.data.minutes }} minutes.
      {% else %}
      {{ trigger.event.data.attraction_name }} is recommended. It has a queue length of {{ trigger.event.data.minutes }} minutes.
      {% endif %}
- choose: []
  default: !input actions
- alias: "Wait for a response"
  wait_for_trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "{{ action_complete }}"
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "{{ action_ignore }}"
- alias: "Perform the action"
  choose:
    - conditions: "{{ wait.trigger.event.data.action == action_complete }}"
      sequence:
        - service: todo.update_item
          data:
            status: completed
            item: >
              {{ trigger.event.data.attraction_id }}
          target:
            entity_id: !input todo_list
