reset_remaining_attractions:
  name: Resets remaining attractions
  description: Rests the remaining attractions list with all attractions for the associated park.
  target:
    entity:
      integration: theme_park_assistant
      domain: todo
    